name: Build & Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main   # change this if your default branch is 'master'

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.6'  # pinned version instead of 'stable'

      - name: Get dependencies
        run: flutter pub get

      - name: Build Flutter web (release)
        run: flutter build web --release --dart-define=OPENWEATHER_API_KEY=${{ secrets.OPENWEATHER_API_KEY }}

      - name: Fix base href for GitHub Pages
        run: |
          if [ -f build/web/index.html ]; then
            sed -i 's|<base href=\"/\">|<base href=\"./\">|' build/web/index.html
          fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web
